title: Aery32 devzone
url: http://devzone.aery32.com

markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title

lsi: true
paginate: 20

exclude:
- CNAME
- .gitignore

urls:
- ['Home', '/']
- ['Archive', '/archive']