title: Aery32 DevZone
url: http://devzone.aery32.com

markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title

lsi: true
paginate: 20

exclude:
- CNAME
- .gitignore

# Navigation
urls:
- ['Home', '/', 'home']
- ['Archive', '/archive', 'th']